const questions = [
    {
      question: "Which characteristic is commonly used to compare processors?",
      options: [
        "A) Cache size",
        "B) Number of USB ports",
        "C) Color of the casing",
        "D) Brand name"
      ],
      answer: "A) Cache size",
      image: require('../assets/processors.jpg'),

    },
    {
      question: "What is the primary benefit of upgrading a processor?",
      options: [
        "A) Improved graphics performance",
        "B) Increased speed and efficiency in processing tasks",
        "C) More storage capacity",
        "D) Enhanced sound quality",
      ],
      answer: "B) Increased speed and efficiency in processing tasks",
      image: require('../assets/processors.jpg'),
    },
    {
      question: "Which type of memory is volatile and loses its data when powered off?",
      options: [
        "A) ROM",
        "B) SSD",
        "C) RAM",
        "D) Hard Drive"
      ],
      answer: "C) RAM",
      image: require('../assets/processors.jpg'),
    },
    {
      question: "What does the term 'DDR' in DDR RAM stand for?",
      options: [
        "A) Dynamic Data Rate",
        "B) Double Data Rate",
        "C) Direct Data Read",
        "D) Dual Data Rate"
      ],
      answer: "B) Double Data Rate",
      image: require('../assets/processors.jpg'),
    },
    {
      question: "What is the first step in installing a new processor?",
      options: [
        "A) Connecting the power supply",
        "B) Placing the processor into the socket",
        "C) Removing the old processor",
        "D) Installing the heat sink"
      ],
      answer: "C) Removing the old processor",
      image: require('../assets/processors.jpg'),
    },
    {
      question: "What is a key difference between DDR3 and DDR4 RAM?",
      options: [
        "A) DDR4 has a lower voltage requirement",
        "B) DDR3 is faster than DDR4",
        "C) DDR4 is physically larger than DDR3",
        "D) DDR3 is more expensive"
      ],
      answer: "A) DDR4 has a lower voltage requirement",
      image: require('../assets/processors.jpg'),
    },
    {
      question: "Which of the following statements about processors is true?",
      options: [
        "A) All processors are compatible with any motherboard",
        "B) Processors have different socket types",
        "C) More cores always mean better performance",
        "D) Processors do not require cooling solutions"
      ],
      answer: "B) Processors have different socket types",
      image: require('../assets/processors.jpg'),
    },
    {
      question: "What is the purpose of a heat sink in a CPU setup?",
      options: [
        "A) To store data",
        "B) To increase processing speed",
        "C) To dissipate heat generated by the CPU",
        "D) To enhance graphics"
      ],
      answer: "C) To dissipate heat generated by the CPU",
      image: require('../assets/processors.jpg'),
    },
    {
      question: "Which type of RAM is typically used for high-performance gaming?",
      options: [
        "A) DRAM",
        "B) SRAM",
        "C) SDRAM",
        "D) DDR4"
      ],
      answer: "D) DDR4",
      image: require('../assets/processors.jpg'),
    },
    {
      question: "What does 'virtual memory' refer to?",
      options: [
        "A) Physical RAM installed in the system",
        "B) Memory on a hard drive used to extend RAM capacity",
        "C) Memory that is not accessible by the CPU",
        "D) A type of cache memory"
      ],
      answer: "B) Memory on a hard drive used to extend RAM capacity",
      image: require('../assets/processors.jpg'),
    },
    {
      question: "What could happen if a CPU is not properly seated in its socket?",
      options: [
        "A) The CPU may overheat",
        "B) The computer will not boot",
        "C) The motherboard will be damaged",
        "D) All of the above"
      ],
      answer: "D) All of the above",
      image: require('../assets/processors.jpg'),
    },
    {
      question: "What does the term 'multi-threading' refer to in CPU design?",
      options: [
        "A) The ability of a CPU to perform multiple tasks simultaneously using multiple cores",
        "B) The technique of improving the speed of a single task by splitting it into smaller threads",
        "C) The ability to run multiple applications at the same time without crashing",
        "D) A method for increasing the CPU's clock speed"
      ],
      answer: "A) The ability of a CPU to perform multiple tasks simultaneously using multiple cores",
      image: require('../assets/processors.jpg'),
    }
    
  ];
  
  export default questions;
  